name: Publish API docs

on:
  workflow_run:
    workflows: ["Validate iMednet OpenAPI specification"]
    types:
      - completed
  workflow_dispatch:

jobs:
  docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ── OPTION A – ReDoc (richer UI) ───────────────────────────
      - uses: actions/setup-node@v4
      - run: npx redoc-cli bundle imednet/openapi.yaml -o site/index.html
        # add --options.theme.colors.primary.main=... etc. if desired

      # ── Publish to GitHub Pages ────────────────────────────────
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - uses: actions/deploy-pages@v4
