name: Validate OpenAPI spec

on:
  push:
    branches: [main]
    paths: [spec/openapi.yaml]
  workflow_dispatch: {}

jobs:
  validate-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Validate specification
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/local" \
            openapitools/openapi-generator-cli validate \
            -i /local/spec/openapi.yaml
  test:
    runs-on: ubuntu-latest
    needs: validate-spec
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
